steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/datapath-ai17-kevin-inofuente/repositorio-backend-langgraph-multiagente/image-backend-langgraph-multiagente:v1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/datapath-ai17-kevin-inofuente/repositorio-backend-langgraph-multiagente/image-backend-langgraph-multiagente:v1']